title: The Site
author: Mark Pugner
email: adam@curry.com
description: > # this means to ignore newlines until "baseurl:"
  the site's description

# social links
twitter_username: therealdvorak # DO NOT include the @ character, or else the build will fail!
github_username:  mygihubhandle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
